### ISSUE TITLE
GFM's emoji doesn't seem to be parsed

### ISSUE THREAD

**Issue by ogwata** [vivliostyle/create-book#10]
- manuscript.md
```
`:EMOJICODE:`
`:クラッカー: :両目: :花束:`
:クラッカー: :両目: :花束:
```

- manuscript.html
```
<p><code>:EMOJICODE:</code><br>
<code>:クラッカー: :両目: :花束:</code><br>
:クラッカー: :両目: :花束:</p>
```

- mybook.pdf

<img width="174" alt="スクリーンショット 2020-08-07 17 03 56" src="https://user-images.githubusercontent.com/31482860/89623671-ffd1f080-d8cf-11ea-93af-3a219011be23.png">

**Comment by spring-raining** [comment]
That specification does not accepted yet. https://github.com/vivliostyle/vfm/issues/13
