### ISSUE TITLE
code: 'MODULE_NOT_FOUND' というエラーが出る

### ISSUE THREAD

**Issue by ogwata** [vivliostyle/create-book#2]
`npm create book MyBook`を実行したところ、`code: 'MODULE_NOT_FOUND'`というエラーが出ました。
何が悪いのでしょう？

<img width="870" alt="スクリーンショット 2020-07-19 0 55 47" src="https://user-images.githubusercontent.com/31482860/87856505-a9216880-c95a-11ea-8760-097ca6723c8a.png">

**Comment by uetchy** [comment]
Nodeのバージョンは何ですか？ `node -v`

**Comment by ogwata** [comment]
v13.0.1です。

**Comment by ogwata** [comment]
村上さんにサポートしていただき無事解決しました。
node.js v13.0.1のインストール後、Vivliostyle.jsのフォルダを移動させていたのが原因でした。
別のバージョン（v12.18.2）をインストールし、nodebrewでこちらに切り換えて実行したところ、無事に本が作れました。
キャプチャを添付します。
<img width="851" alt="スクリーンショット 2020-07-20 17 20 38" src="https://user-images.githubusercontent.com/31482860/87924269-9a9d9300-cab9-11ea-8dcb-87943c295bc2.png">
<img width="846" alt="スクリーンショット 2020-07-20 18 52 50" src="https://user-images.githubusercontent.com/31482860/87924747-42b35c00-caba-11ea-8ae3-73fb530aec07.png">
