### ISSUE TITLE
Rename create-book to create-vivliostyle-project

### ISSUE THREAD

**Issue by uetchy** [vivliostyle/create-book#4]
Because `create-book` often misleads users that it can be used to build a book than creating a project template.

**Comment by MurakamiShinyu** [comment]
"create-book" という名前はこのままのほうが良いと思います。
- "Vivliostyle Project" は Vivliostyle そのものの開発プロジェクトの意味で使われてきています。
- 作ることができるのは本だけではないが（スライドなども）、複数ページからなるページものは、本のようなものであるので、本などを作れる（作り始めることができる）ツールとして、この名前は違和感はない。
- `npm create book` で作られるのは本を作るプロジェクトであるが、 そこで build を実行すると組版されて本ができるというものであるので、使う側からすると "create-book" というツールによってプロジェクト（雛形）ができるだけでなく、本を作る（本を組版する）ところまでできるということになる。 "it can be used to build a book" というのはミスリードとはいえない。（ユーザーは Vivliostyle CLI など別のツールが動いていることは気にする必要がない）
- npmjs.com に登録されるパッケージ名として "create-book" のようなシンプルな名前がそれまで誰にも登録されていなくて、この "create-book" で使うことができたのはラッキーです。そのメリットをいかしてよいと思います。

**Comment by uetchy** [comment]
既に勘違いした使用例がSlackで報告されているので、もう少し明示的な名前にしたいです。vivliostyle-projectは確かに良くないネーミングなので他のアイディアが必要ですね。

**Comment by ogwata** [comment]
8月初頭を目指して、Create Bookのチュートリアルを公開するよう作業中です。
その意味から、重大なトラブルがない限り、できればリネームは回避していただきたいのが正直なところです。

なお、別件ですがチュートリアルの構成案をSlackで議論中です。
下記からご確認いただけませんか。
https://vivliostyle.slack.com/archives/CNN5GPF9V/p1595865678127900

**Comment by MurakamiShinyu** [comment]
create-book というパッケージ名はそのままにして、このツールの説明をするときに「Create Book スターターキット」(Create Book starter kit) と呼ぶようにするのはどうでしょう？ 本を作り始めるのに使うものだということがイメージしやすいかなと思います。

Yarnのcreateコマンドの説明に「スターターキット(starter kits)」が使われています：
https://classic.yarnpkg.com/ja/docs/cli/create
https://classic.yarnpkg.com/en/docs/cli/create

**Comment by ogwata** [comment]
「Create Book スターターキット」（Create Book starter kit）に賛成です。「本作りのためのプロジェクトを作る」というCreate Bookの性質をよく言い表していると思います。

**Comment by spring-raining** [comment]
一つの案としては、https://github.com/vivliostyle/vivliostyle-cli をmonorepo化して、vivliostyle-cliの一つのpackageとして管理するというのはどうでしょうか？ CLI関連のプロジェクトをまとめると、より役割が分かりやすくなると思います。

**Comment by youchan** [comment]
Create Bookはシンプルでいいなと思っていたのですが、あえて名前を変えるなら、
Create Book Projectとかがいいかなーと思いました。

**Comment by MurakamiShinyu** [comment]
名前は Create Book (create-book) のままでよいとみなさん同意されたようですので、閉じます。
異論があれば再オープンしてください
